### ISSUE TITLE
Inconsistent problems with backend token swap

### ISSUE THREAD

**Issue by Davidorenlane** [spotify/ios-sdk#152]
Hi Guys,

I am having a problem with the Authorization code flow. I am running the provided ruby script (spotify_token_swap.rb) as prescribed in the documentation with Sinatra on my machine. I use the same code for sessionManager and configuration as was used in the example code. The only change I have made is that I have allowed requests to come in via my home router and be forwarded to the port so that connections are possible from any internet connection. 

80% of the time, this works and users are able to authenticate normally. The other 20% or so, the users appear to be authorized (they are routed to Spotify app and see the check mark, then they are returned to my app) but they do not get a valid token. I think the problem is with the backend token swap. Here is my terminal from today (server was running all night).

```
159.65.119.71 - - [20/Sep/2019:00:50:21 -0700] "GET /admin/config.php HTTP/1.1" 404 478 0.0319
159.65.119.71 - - [20/Sep/2019:00:50:21 PDT] "GET /admin/config.php HTTP/1.1" 404 478
- -> /admin/config.php
[2019-09-20 02:45:36] ERROR bad Request-Line `GET ../../mnt/custom/ProductDefinition HTTP'.
125.59.115.17 - - [20/Sep/2019:02:45:36 PDT] "GET ../../mnt/custom/ProductDefinition HTTP" 400 329
- -> 
177.200.66.129 - - [20/Sep/2019:04:57:49 -0700] "GET / HTTP/1.1" 404 457 0.0174
177.200.66.129 - - [20/Sep/2019:04:57:49 PDT] "GET / HTTP/1.0" 404 457
- -> /
103.87.47.145 - - [20/Sep/2019:05:26:59 -0700] "GET / HTTP/1.1" 404 457 0.0073
103.87.47.145 - - [20/Sep/2019:05:26:58 PDT] "GET / HTTP/1.1" 404 457
- -> /
179.110.254.213 - - [20/Sep/2019:06:05:51 -0700] "GET / HTTP/1.1" 404 457 0.0099
179.110.254.213 - - [20/Sep/2019:06:05:51 PDT] "GET / HTTP/1.1" 404 457
- -> /
159.203.201.10 - - [20/Sep/2019:06:28:43 -0700] "GET / HTTP/1.1" 404 457 0.0123
159.203.201.10 - - [20/Sep/2019:06:28:43 PDT] "GET / HTTP/1.1" 404 457
- -> /
216.165.95.190 - - [20/Sep/2019:07:32:46 -0700] "POST /swap HTTP/1.1" 200 594 0.4195
216.165.95.190 - - [20/Sep/2019:07:32:45 PDT] "POST /swap HTTP/1.1" 200 594
- -> /swap
[2019-09-20 07:32:49] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:12 
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `eof?'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:314:in `block in start_thread'
177.105.239.254 - - [20/Sep/2019:07:38:31 -0700] "GET / HTTP/1.1" 404 457 0.0061
177.105.239.254 - - [20/Sep/2019:07:38:31 PDT] "GET / HTTP/1.1" 404 457
- -> /
45.50.169.233 - - [20/Sep/2019:08:53:54 -0700] "POST /swap HTTP/1.1" 200 611 0.4606
45.50.169.233 - - [20/Sep/2019:08:53:53 PDT] "POST /swap HTTP/1.1" 200 611
- -> /swap
[2019-09-20 08:54:03] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:12 
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `eof?'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:314:in `block in start_thread'
172.56.3.110 - - [20/Sep/2019:08:56:36 -0700] "POST /swap HTTP/1.1" 200 595 0.3042
172.56.3.110 - - [20/Sep/2019:08:56:36 PDT] "POST /swap HTTP/1.1" 200 595
- -> /swap
45.50.169.233 - - [20/Sep/2019:08:57:00 -0700] "POST /swap HTTP/1.1" 200 611 0.3045
45.50.169.233 - - [20/Sep/2019:08:57:00 PDT] "POST /swap HTTP/1.1" 200 611
- -> /swap
[2019-09-20 08:57:11] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:12 
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `eof?'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/webrick/server.rb:314:in `block in start_thread'
107.155.153.168 - - [20/Sep/2019:09:06:04 -0700] "GET / HTTP/1.1" 404 457 0.0079
107.155.153.168 - - [20/Sep/2019:09:06:04 PDT] "GET / HTTP/1.1" 404 457
- -> /
78.154.160.134 - - [20/Sep/2019:09:30:03 -0700] "GET / HTTP/1.1" 404 457 0.0141
78.154.160.134 - - [20/Sep/2019:09:30:03 PDT] "GET / HTTP/1.0" 404 457
- -> /
```

It seems like the first two requests could be a port scanning attack (which I should probably deal with) but many of the requests in the middle are legitimate (My sister) but should have come in as POSTs not GETs. Every time so far, the user has been able to simply reboot the app and try again and it works. 

I'm not sure the problem, but hopefully you all can give suggestions.

Thanks,
David

**Comment by patrice4github** [comment]
Your swap request come in a POST just fine.

There's something querying the root of your RoR server, that's another thing. Feel free to attach your spotify controller code, I'll look at it.
